# couldnt really rewrite so - inspired by noblox: https://github.com/suufi/noblox.js/blob/master/.travis.yml

language: node_js
node_js:
  - "12"

before_install:
  - yarn install

script:
  - yarn lint

branches:
  except:
    - gh-pages